version: "3.9"

services:
  db:
    build: .
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./my_files
        target: /my_files_from_host

      - type: bind
        source: ./db_data
        target: /var/lib/postgresql/data